post_user_create:
  path: /user/create
  controller: App\Controller\UserController::createUser

get_user_info:
  path: /user
  controller: App\Controller\UserController::getUserInfo

post_upload_an_attachment:
  path: /user/attachment
  controller: App\Controller\UserController::uploadAttachment

post_send_mail:
  path: /mail/send
  controller: App\Controller\UserController::sendMail

get_mail_info:
  path: /mail
  controller: App\Controller\UserController::getMailInfo
